//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gameblog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public Review()
        {
            this.Photos = new HashSet<Photo>();
            this.Videos = new HashSet<Video>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string body1 { get; set; }
        public string title { get; set; }
        public Nullable<int> subcat_id { get; set; }
        public Nullable<System.DateTime> timeStamp { get; set; }
        public string body2 { get; set; }
    
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
